version: "3.4"

services:
    web:
        image: ambientum/php:7.4-nginx
        container_name: laravel-docker
        volumes:
        - .:/var/www/app:delegated
        ports:
        - 8000:8080
        depends_on:
        - mysql-app
        environment:
        - PHP_MEMORY_LIMIT=-1
        - COMPOSER_MEMORY_LIMIT=-1
        networks:
            - app-network
    mysql-app:
        image: mysql:5.7.22
        restart: always
        volumes:
            - .dbdata:/var/lib/mysql
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        ports:
            - ${DB_PORT}:3306
        networks:
            - app-network
networks:
  app-network:
    driver: bridge
